repeat wait() until game:IsLoaded() and game.Players.LocalPlayer:FindFirstChild("DataLoaded")
repeat wait(1) 
until game.Players.LocalPlayer.Team ~= nil and game.Players.LocalPlayer.Character and game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/vinh129150/hack/refs/heads/main/Notify.lua"))()
end)
spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/noguchihyuga/idk/refs/heads/main/abcyxz.lua"))()
end)
spawn(function()
    loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NotifyBloxKid.luau"))()
end)
spawn(function()
loadstring(game:HttpGet("https://luacrack.site/index.php/concacmaydaitoinach/raw/Notify"))()
end)
spawn(function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/RealMatsune/DragonToroModel/refs/heads/main/model.lua"))()
end)
spawn(function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/WhiteX1208/Scripts/refs/heads/main/CauTrom.luau"))()
end)
wait(1)
spawn(function()
    loadstring(game:HttpGet("https://luacrack.site/index.php/TBoyRoblox/raw/GravityHub-BloxFruit"))()
end)